drop table autentificare;
create table autentificare
(
    id number(5, 0) GENERATED by default on null as IDENTITY,
	username varchar(30) not null,
	password varchar(30) not null	
);

ALTER TABLE autentificare
ADD CONSTRAINT user_pk PRIMARY KEY (username);

alter table autentificare
add constraint id2_fk
foreign key (id) references emp(id); 

insert into autentificare values(NULL, 'Ana', 'password');
insert into autentificare values(NULL, 'Sergiu', 'password');
insert into autentificare values(NULL, 'Marius', 'secret');
insert into autentificare values(NULL, 'Alex21', 'password');
insert into autentificare values(NULL, 'Marc44', 'secret');

commit;

select * from autentificare;