drop table emp;
create table emp(
	id number(5, 0) GENERATED by default on null as IDENTITY,
	first_name varchar2(30) not null,
	last_name varchar2(30) not null,
	username varchar2(30) not null
);

alter table emp
add constraint id_pk2 primary key (id);

insert into emp values(NULL, 'C1', 'Ana', 'Ana');
insert into emp values(NULL, 'C2', 'Sergiu', 'Sergiu');
insert into emp values(NULL, 'C3', 'Marius', 'Marius');
insert into emp values(NULL, 'C4', 'Alex', 'Alex21');
insert into emp values(NULL, 'C5', 'Marc', 'Marc44');

commit;

select * from emp;
